run llm BUT still have minor issues
langchain.schema.output_parser.OutputParserException: Got invalid JSON object

might need to change the parser to json object parser and rewrite some code